# Generated by Django 4.1.3 on 2022-11-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='payment category')),
            ],
            options={
                'verbose_name': 'payment category',
                'verbose_name_plural': 'payment categories',
            },
        ),
    ]
