# Generated by Django 4.1.3 on 2022-11-09 17:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_journal', '0001_create_category_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='money')),
                ('date_created', models.DateTimeField(verbose_name='date created')),
                ('organization', models.CharField(max_length=80, verbose_name='organization')),
                ('discription', models.TextField(max_length=500, verbose_name='description for payment')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_journal.category')),
            ],
            options={
                'verbose_name': 'income note',
                'verbose_name_plural': 'income notes',
            },
        ),
    ]
